#!/usr/bin/env bash

# Get data if missing and unzip to ./data
mkdir -p data
if [ ! -f "data/README_h2" ]; then
  echo "[Info] Fetching dataset zip if not present..."
  if [ ! -f "h2-data.zip" ]; then
    if command -v curl >/dev/null 2>&1; then
      curl -L -o h2-data.zip "https://engineering.purdue.edu/ece595cv/h2-data.zip"
    else
      wget -O h2-data.zip "https://engineering.purdue.edu/ece595cv/h2-data.zip"
    fi
  fi
  unzip -q -o h2-data.zip -d data
  echo "ok" > data/README_h2
fi

# Train
python train.py

# Test
python test.py
